version: "3.8"
networks:
  default:
    name: mongodb_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - paintingAppData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      default:
        ipv4_address: 172.18.0.2
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 443:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_BASICAUTH_USERNAME=matan
      - ME_CONFIG_BASICAUTH_PASSWORD=matan95
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      default:
        ipv4_address: 172.18.0.3
  painting-app:
    image: mpizman/demo:0.0.3
    container_name: paintings-app
    restart: always
    ports:
      - 80:8080
    links:
      - "mongodb:mongo"
    networks:
      default:
        ipv4_address: 172.18.0.4
volumes:
  paintingAppData:
